### ISSUE TITLE
Crash on launch running from Xcode

### ISSUE THREAD

**Issue by darknoon** [SamSchott/maestral-cocoa#23]
macOS 12.1 Beta (21C5031d)
Xcode Version 13.2 beta (13C5066c)

- Checkout project (hash 882d0128382cf7492afbb1825a69db6ddd16dae4)
- Opened Xcode project in Xcode
- Hit run

Get this error:

<img width="744" alt="Screen Shot 2021-11-15 at 10 38 04 AM" src="https://user-images.githubusercontent.com/355540/141810028-5fad7bc6-c418-4f7a-8f4c-366804d4897f.png">

```
Traceback (most recent call last):
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/__main__.py", line 43, in <module>
    main()
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/__main__.py", line 14, in main
    from .app import run
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/app.py", line 53, in <module>
    from .settings import SettingsWindow
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/settings.py", line 24, in <module>
    from .settings_gui import SettingsGui
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/settings_gui.py", line 24, in <module>
    from .constants import FROZEN
  File "Maestral.app/Contents/Resources/app/maestral_cocoa/constants.py", line 14, in <module>
    _md = metadata(_app_module)  # type: ignore
  File "Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.9/importlib/metadata.py", line 541, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: maestral_cocoa
```
The correct files seem to be there in the filesystem:

<img width="1144" alt="Screen Shot 2021-11-15 at 10 39 13 AM" src="https://user-images.githubusercontent.com/355540/141810203-63da6853-0c56-459f-8698-9fd1fc66758f.png">

App log:

```
2021-11-15 10:36:15.163830-0500 Maestral[14540:2883538] PythonHome is: /Users/andrew/Library/Developer/Xcode/DerivedData/Maestral-fprtcjkhfsvfgmdrhyjjibotgckk/Build/Products/Debug/Maestral.app/Contents/Resources/Support/Python/Resources
2021-11-15 10:36:15.164877-0500 Maestral[14540:2883538] PYTHONPATH is: PYTHONPATH=/Users/andrew/Library/Developer/Xcode/DerivedData/Maestral-fprtcjkhfsvfgmdrhyjjibotgckk/Build/Products/Debug/Maestral.app/Contents/Resources/app:/Users/andrew/Library/Developer/Xcode/DerivedData/Maestral-fprtcjkhfsvfgmdrhyjjibotgckk/Build/Products/Debug/Maestral.app/Contents/Resources/app_packages
2021-11-15 10:36:15.164916-0500 Maestral[14540:2883538] Initializing Python runtime...
2021-11-15 10:36:15.214311-0500 Maestral[14540:2883538] Installing Python NSLog handler...
2021-11-15 10:36:15.257423-0500 Maestral[14540:2883538] Running app module: maestral_cocoa
2021-11-15 10:36:15.690637-0500 Maestral[14540:2883538] Application quit abnormally!
```

**Comment by SamSchott** [comment]
Yes, that's a known problem.

The Xcode project is created automatically from the Python project using a tool called [briefcase](https://github.com/beeware/briefcase), including all the package metadata. `briefcase` has the bad habit of keeping old metadata around, even after updating all Python packages in the Xcode project.

To prevent metadata folders from piling up, I simply added them to gitignore and populate the latest metadata just before building in CI. This is probably the wrong approach, it would be better to fix the underlying briefcase issue.

I'll add the metadata for now and see if I can work on a fix for `briefcase`.

**Comment by SamSchott** [comment]
If you want to replicate the build by the CI, you will also need to run `scripts/post-build-macos.sh`, giving the created app bundle as an argument. The post-build scripts only do two things:

1. They copy over some additional `entry_points.txt` metadata for `maestral_cocoa` which briefcase does not create. This is required when launching the GUI from the CLI.
2. They convert all `.py` files in the bundle to `.pyc` files. This saves a bit of space and results in faster execution on the first run.
