### ISSUE TITLE
Could not access sys._traceback

### ISSUE THREAD

**Issue by henryzhao95** [samschott/maestral-cocoa#32]
Getting Could not access sys._traceback error launching 1.6.1 GUI. When I build the master branch (1.6.2 beta) from Xcode, the GUI launches fine, so not sure what's going on. Nothing in Maestral.log after turning on debug logging:

2022-03-27 22:54:39 daemon INFO: Starting daemon
2022-03-27 22:54:40 manager INFO: Connected
2022-03-27 22:55:51 sync INFO: Sync aborted
2022-03-27 22:55:51 manager INFO: Paused
2022-03-27 22:55:53 daemon INFO: Starting daemon
2022-03-27 22:55:53 daemon DEBUG: Environment:
{'COMMAND_MODE': 'unix2003',
 'HOME': '/Users/henry',
 'LC_CTYPE': 'UTF-8',
 'LOGNAME': 'henry',
 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin',
 'PYTHONDONTWRITEBYTECODE': '1',
 'PYTHONOPTIMIZE': '2',
 'PYTHONPATH': '/Applications/Maestral.app/Contents/Resources/app:/Applications/Maestral.app/Contents/Resources/app_packages',
 'PYTHONUNBUFFERED': '1',
 'SHELL': '/bin/zsh',
 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.bh5aYZBIAr/Listeners',
 'TMPDIR': '/var/folders/4v/p7gxf09517bbll5yfcd3xm5c0000gn/T/',
 'USER': 'henry',
 'XPC_FLAGS': '0x0',
 'XPC_SERVICE_NAME': 'application.com.samschott.maestral.14857337.14857589',
 '__CFBundleIdentifier': 'com.samschott.maestral',
 '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0xF'}

2022-03-27 22:55:53 daemon DEBUG: Acquired daemon lock: '/Users/henry/Library/Application Support/maestral/maestral.lock'
2022-03-27 22:55:53 daemon DEBUG: Integrating with CFEventLoop
2022-03-27 22:55:53 daemon DEBUG: Socket path: '/Users/henry/Library/Application Support/maestral/maestral.sock'
2022-03-27 22:55:53 daemon DEBUG: Creating Pyro daemon
2022-03-27 22:55:53 sync DEBUG: Could not load mignore rules: No such file or directory
2022-03-27 22:55:53 daemon DEBUG: Starting event loop
2022-03-27 22:55:54 manager INFO: Connected

I've also attached the files being read by the release vs. Xcode processes.

[xcode.txt](https://github.com/samschott/maestral-cocoa/files/8357524/xcode.txt)
[release.txt](https://github.com/samschott/maestral-cocoa/files/8357525/release.txt)

**Comment by samschott** [comment]
Thanks for the report!

The enigmatic message is due to some exception handling code which I did not clean up properly. Something is failing during startup and you should be seeing a window with an actual traceback instead of "Could not access sys._traceback".

It is surprising though that `1.6.2.dev0` runs without problems, there have been almost no changes.

Could you try launching the stable version `1.6.1` from the Terminal by running `/Applications/Maestral.app/Contents/MacOS/Maestral`? This should hopefully print a more informative traceback to the console.

**Comment by henryzhao95** [comment]
Thanks @samschott, found the traceback and fixed the issue by deleting my x86_64 Sparkle folder.

Traceback (most recent call last):
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/runpy.py", line 87, in _run_code
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 43, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 20, in main
  File "Contents/Resources/app/maestral_cocoa/app.py", line 499, in run
  File "Contents/Resources/app_packages/toga/app.py", line 511, in main_loop
  File "Contents/Resources/app_packages/toga_cocoa/app.py", line 338, in main_loop
  File "Contents/Resources/app/maestral_cocoa/private/implementation/cocoa/factory.py", line 809, in create
  File "Contents/Resources/app/maestral_cocoa/app.py", line 114, in startup
  File "Contents/Resources/app/maestral_cocoa/updater.py", line 211, in __init__
  File "Contents/Resources/app/maestral_cocoa/updater.py", line 84, in __init__
  File "Contents/Resources/app_packages/rubicon/objc/runtime.py", line 61, in load_library
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/Library/Frameworks/Sparkle.framework/Sparkle, 0x0006): tried: '/Library/Frameworks/Sparkle.framework/Sparkle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/System/Library/Frameworks/Sparkle.framework/Sparkle' (no such file), '/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/System/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file)

**Comment by samschott** [comment]
Hrmp, it should not be trying to load `/Library/Frameworks/Sparkle.framework` but rather the Sparkle framework bundled with the app itself 😠 See here:

https://github.com/samschott/maestral-cocoa/blob/9db02b14bb56620f6237734e99e596bb28bdefef/src/maestral_cocoa/updater.py#L83-L84

This uses `ctypes.util.find_library()` under the hood, I guess I misunderstood how it handles absolute paths. What does
```Python
from ctypes import util
path = "/Applications/Maestral.app/Contents/Frameworks/Sparkle.framework/Sparkle"
util.find_library(path)
```
return on your system if you still have Sparkle installed globally?

**Comment by henryzhao95** [comment]
henry@Henrys-Mac ~ % python3
Python 3.9.10 (main, Jan 15 2022, 11:40:53) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import util
>>> path = "/Applications/Maestral.app/Contents/Frameworks/Sparkle.framework/Sparkle"
>>> util.find_library(path)
'/Library/Frameworks/Sparkle.framework/Sparkle'

**Comment by samschott** [comment]
Thanks! That's what I was suspecting.
